// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID          uuid.UUID      `json:"id"`
	Username    sql.NullString `json:"username"`
	Email       sql.NullString `json:"email"`
	Password    string         `json:"password"`
	PhoneNumber string         `json:"phone_number"`
	Role        int32          `json:"role"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}
