// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (phone_number, password)
VALUES ($1, $2)
`

type CreateUserParams struct {
	PhoneNumber string `json:"phone_number"`
	Password    string `json:"password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser, arg.PhoneNumber, arg.Password)
	return err
}

const existUserByPhoneNumber = `-- name: ExistUserByPhoneNumber :one
SELECT EXISTS(SELECT 1
              FROM users
              WHERE phone_number = $1) as exists
`

func (q *Queries) ExistUserByPhoneNumber(ctx context.Context, phoneNumber string) (bool, error) {
	row := q.db.QueryRowContext(ctx, existUserByPhoneNumber, phoneNumber)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getUserById = `-- name: GetUserById :one
SELECT id,
       username,
       email,
       phone_number,
       role,
       password,
       created_at,
       updated_at
FROM users
WHERE id = $1
`

type GetUserByIdRow struct {
	ID          uuid.UUID      `json:"id"`
	Username    sql.NullString `json:"username"`
	Email       sql.NullString `json:"email"`
	PhoneNumber string         `json:"phone_number"`
	Role        int32          `json:"role"`
	Password    string         `json:"password"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (GetUserByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i GetUserByIdRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PhoneNumber,
		&i.Role,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByPhoneNumber = `-- name: GetUserByPhoneNumber :one
SELECT id,
       username,
       email,
       phone_number,
       role,
       password,
       created_at,
       updated_at
FROM users
WHERE phone_number = $1
`

type GetUserByPhoneNumberRow struct {
	ID          uuid.UUID      `json:"id"`
	Username    sql.NullString `json:"username"`
	Email       sql.NullString `json:"email"`
	PhoneNumber string         `json:"phone_number"`
	Role        int32          `json:"role"`
	Password    string         `json:"password"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

func (q *Queries) GetUserByPhoneNumber(ctx context.Context, phoneNumber string) (GetUserByPhoneNumberRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByPhoneNumber, phoneNumber)
	var i GetUserByPhoneNumberRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PhoneNumber,
		&i.Role,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
